# Use an official OpenJDK runtime as a parent image
FROM eclipse-temurin:25-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the executable jar file
COPY target/*.jar app.jar

# Run the jar file
ENTRYPOINT ["java", "-jar", "app.jar"]
