server:
  servlet:
    context-path: /promptvault

spring:
  profiles:
    active: localhost
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresql.woods.local:5432/prompt-vault-dev}
    username: ${SPRING_DATASOURCE_USERNAME:prompt-vault}
    password: ${SPRING_DATASOURCE_PASSWORD:lu55KkdVZrlyAb}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: prompt-vault
  sql:
    init:
      mode: never

  flyway:
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 604800000 # 7 days in milliseconds
